config/routes.rb
CoffeeSpec::Application.routes.draw do

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#fail'

  resources :companies, :only => [:show, :update] do
    resources :drinks
  end
  resource :sessions

  match "/drinks/:drink_token/wants" => "drinks#wants"
  match "/drinks/:drink_token/making" => "drinks#making"
  match "/drinks/:drink_token/edit" => "drinks#edit_with_token"

  match "/t/:token" => "application#token_route", :as => :token

  root :to => "application#landing"

  match "*path" => "application#not_found" #404

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :user_id, :edit_token, :view_token

  belongs_to :user
  has_many :drinks
  belongs_to :currently_making, :class_name => :drink
  before_create :generate_tokens

  scope :find_by_token, lambda {|token| where("view_token = ? OR edit_token = ?", token, token) }

  private

  def generate_tokens
    self.view_token = generate_token
    self.edit_token = generate_token
  end

  def generate_token
    token = Company.random_token
    token = Company.random_token while Company.has_token?(token)
    token
  end

  def self.has_token?(token)
    Company.find_by_token(token).count > 0
  end

  def self.random_token
    SecureRandom.urlsafe_base64(6)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  include CompanySupport

  before_filter :must_view, :only => [:show]
  before_filter :must_edit, :only => [:update]

  def show
    @drinks = @company.drinks
    @break_room = params.include? "breakroom"
  end

  def update
    if can_edit? and @company.update_attribute(:name, params[:name])
      render :inline => @company.name
    else
      render :nothing => true, :status => :bad_request
    end
  end

  private

end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/companies/_toolbar.html.haml
- if @break_room
  %a.btn.btn-large.notify{:href => "javascript:;"}
    %i.icon-bullhorn
    Notify Everyone
- else
  .btn-toolbar.pull-right
    .btn-group
      %a.btn.btn-medium.notify{:href => "javascript:;"}
        %i.icon-bullhorn
        Notify Everyone
      %a.btn.btn-medium.print{:href => "javascript:window.print()"}
        %i.icon-print
        Print spec
      %a.btn.btn-medium.share{:href => token_url(:token => @company.view_token)}
        %i.icon-share
        Share URL
      - if can_edit?
        %a.btn.btn-medium.share.edit{:href => token_url(:token => @company.edit_token)}
          %i.icon-edit
          Share Edit URL

app/views/companies/show.html.haml
!= render :partial => 'common/page_header', :locals => {:company => @company}
!= render :partial => "toolbar"
:erb
  <script type='text/javascript'>
    $(function() {
      CoffeeSpec.drinksController.loadAll(<%= @drinks.to_json %>);
      CoffeeSpec.drinkTypeController.update(<%= Drink::DRINK_TYPES.keys.to_json %>);
      CoffeeSpec.strengthController.update(<%= Drink::DRINK_ASPECTS[:strength].to_json %>);
      CoffeeSpec.milkTypesController.update(<%= Drink::DRINK_ASPECTS[:milk][:type].to_json %>);
      CoffeeSpec.milkAmountController.update(<%= Drink::DRINK_ASPECTS[:milk][:amount].to_json %>);
      CoffeeSpec.sugarAmountController.update(<%= Drink::DRINK_ASPECTS[:sugar][:amount].to_json %>);
      CoffeeSpec.sugarTypeController.update(<%= Drink::DRINK_ASPECTS[:sugar][:type].to_json %>);
      CoffeeSpec.teaVariationController.update(<%= Drink::DRINK_ASPECTS[:tea_variation].to_json %>);
      CoffeeSpec.juiceVariationController.update(<%= Drink::DRINK_ASPECTS[:juice_variation].to_json %>);
      CoffeeSpec.softDrinkVariationController.update(<%= Drink::DRINK_ASPECTS[:soft_drink_variation].to_json %>);
     });
  </script>

.drinks
  :handlebars
    {{view CoffeeSpec.DrinksView}}
- if @drinks.empty?
  .well
    - if can_edit?
      %h2
        You don't have any drinks.
        = link_to "Add a drink", new_company_drink_path(@company, :token => @token)
        and start brewing.
    - else
      %h2
        There are no drinks for this company
- else
  != render :partial => "common/add_drink"