config/routes.rb
CoffeeSpec::Application.routes.draw do

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#fail'

  resources :companies, :only => [:show, :update] do
    resources :drinks
  end
  resource :sessions

  match "/drinks/:drink_token/wants" => "drinks#wants"
  match "/drinks/:drink_token/making" => "drinks#making"
  match "/drinks/:drink_token/edit" => "drinks#edit_with_token"

  match "/t/:token" => "application#token_route", :as => :token

  root :to => "application#landing"

  match "*path" => "application#not_found" #404

end

app/views/common/_add_drink.haml
.drink_container.span6.add_drink
  %a{:href => new_company_drink_path(@company)}
    != render :partial => "common/drink_infograph", :locals => {:drink => Drink.new(:milk_amount => :little)}
    %h2.name Add Drink

app/views/common/_drink.html.haml
.drink_container.span6
  != render :partial => "common/drink_infograph", :locals => {:drink => drink}
  %h2.name
    = drink.name
  %p.description= drink.description.capitalize
  != render :partial => "common/drink_toolbar", :locals => {:drink => drink}

app/views/common/_drink_infograph.html.haml
.drink{:class => drink.drink_type }
  .teabag
  .milk{:class => milk_classes(drink)}
  .essence{:class => essence_classes(drink)}
  .sugar{:class => sugar_classes(drink)}

app/views/common/_drink_toolbar.html.haml
.btn-group.normal_mode
  - debugger
  %a.btn.btn-small.btn-warning.itsme.hidden{:data => {:token => drink.token}}
    %i.icon-user.icon-white
    It's Me
  - if can_edit?
    %a.btn.btn-small.edit{:href => edit_company_drink_path(drink.company, drink)}
      %i.icon-edit
      Edit
- if can_edit?
  .btn-group.edit_mode{ hide }
    %a.btn.btn-small.save{:href => "javascript:;"}
      %i.icon-ok
      Save
    %a.btn.btn-small.cancel{:href => "javascript:;"}
      %i.icon-remove
      Cancel
    %a.btn.btn-small.delete{:href => "javascript:;"}
      %i.icon-trash
      Delete

app/views/common/_form_error.html.haml
- if @drink.errors[field]
  %span.help-inline
    %ul
      - @drink.errors[field].each do |msg|
        %li= msg

app/views/common/_page_header.html.haml
- content_for :title do
  = "#{company.name} | Coffee.Spec"
.page-header
  %h1
    %span.title
      = company.name
      - if can_edit?
        %i.icon-pencil.edit
    - if can_edit?
      != form_tag company_path(company), :method => :put, :class => "inline hidden" do
        = text_field_tag :name, company.name
        .btn-group.inline-block
          = submit_tag :save, :class => "btn btn"
          = button_tag("cancel", :type => 'reset', :class => "btn btn")

    %small coffee.spec

app/views/common/_radio_buttons.html.haml
.control-group{ form_error(aspect, :data => data) }
  != f.label aspect, aspect.to_s.humanize, :class => "control-label"
  .controls
    - values.each do |option|
      != f.label "#{aspect}.#{option}", :class => "radio inline" do
        != f.radio_button aspect, option
        = option.to_s.humanize
    != render :partial => "common/form_error", :locals => {:field => aspect}

app/views/common/_sample_drink.html.haml
.drink_container.span6.sample
  != render :partial => "common/drink_infograph", :locals => {:drink => drink}
  %h2.name= drink.name
  %p.description= drink.description

app/views/common/_wants.html.haml
.alert.alert-info.want{:data => {:token => wants.token}}
  != image_tag "glypicons/glyphicons_355_announcement.png"
  %strong= wants.name
  wants a drink
  %a.close{"data-dismiss" => "alert"} ×